[variables]
NIXPACKS_WORKING_DIR = "/src"

[phases.setup]
nixPkgs = ["python313"]

[phases.install]
cmds = ["python3 -m pip install -r requirements.txt"]

[start]
cmd = "langgraph dev --host 0.0.0.0 --port ${PORT:-8000}"

